SET FOREIGN_KEY_CHECKS=0;

SET FOREIGN_KEY_CHECKS=1;

ALTER TABLE ib_lectures ADD COLUMN st_lecture_name VARCHAR(200) NULL DEFAULT NULL AFTER `lecture_name`;
ALTER TABLE ib_lectures ADD COLUMN lecture_place VARCHAR(200) NULL DEFAULT NULL AFTER `st_lecture_name`;;